---
os: linux
dist: bionic
language: python
services:
  - docker

stages:
  - linter
  - build

jobs:
  fast_finish: true
  include:
    - stage: linter
      env: image=debian verion=9
      script:
        - >
          docker run --rm -it
          --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
          -v /var/run/docker.sock:/var/run/docker.sock
          -w /tmp/$(basename "$PWD")
          quay.io/ansible/molecule:3.0.4
          molecule lint

    - stage: build
      env:
        - image=debian version=9
        - image=debian version=10
        - image=centos version=6
        - image=centos version=7
        - image=centos version=8
        - image=ubuntu version=16.04
        - image=ubuntu version=18.04
        - image=ubuntu version=19.10
        - image=ubuntu version=20.04
      script:
        - >
          travis_wait 20 sleep infinity & docker run --rm -it --env image=$image
          --env version=$version
          --mount type=bind,source="$(pwd)",target=/tmp/$(basename "$PWD")
          -v /var/run/docker.sock:/var/run/docker.sock
          -w /tmp/$(basename "$PWD")
          quay.io/ansible/molecule:3.0.4
          molecule test

notifications:
  email:
    on_failure: change
    on_success: never
