---
- name: "create user(s) account"
  user:
    name: "{{ item.username }}"
    group: "{{ item.group | default(item.username if users_create_per_user_group else users_group) }}"
    # empty string removes user from all secondary groups
    groups: ["{{ item.groups | join(',') if 'groups' in item else '' }}"]
    shell: "{{ item.shell if item.shell is defined else users_default_shell }}"
    password: "{{ item.password if item.password is defined else users_default_password }}"
    comment: "{{ item.name if item.name is defined else '' }}"
    uid: "{{ item.uid }}"
    home: "{{ item.home | default('/home/' + item.username) }}"
    create_home: "{{ 'yes' if users_create_homedirs else 'no' }}"
    update_password: "{{ item.update_password | default(omit) }}"
  with_items:
    - "{{ users }}"
    - "{{ environment_users }}"
    - "{{ host_users }}"
  tags:
    - users
    - configuration
